data: period_splits.pkl
model_params:
  d_model: 128
  dropout: 0.2
  lookahead: 0
  min_len_for_pred: 81
  num_features: 362
  num_heads: 2
  num_stocks: 3
  pred_features:
  - 0
  - 1
  pred_len: 2
  seq_len: 20
  tickers:
  - GOOGL
  - AMZN
  trained_period:
    end: '2025-01-01'
    start: '2021-10-01'
model_path: stockformer_model.pth
train_params:
  batch_size: 1024
  cla_loss_weight: 2.0
  device: cuda
  epochs: 100
  initial_learning_rate: 0.001
  initial_weight_decay: 0.1
  period_len: 648
  reset_optimizer: true
  train_split: 0.75
  val_split: 0.125
